version: '3.7'

services:

  myapp-main:
    container_name: myapp-main
    image: myapp-main
    depends_on:
      - myapp-mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=LOCAL
      - SPRING_DATASOURCE_URL=jdbc:mysql://myapp-mysql:3306/energizer_project

  myapp-mysql:
    container_name: myapp-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: energizer_project
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: nhinguyen12345

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend
    ports: 
      - "4200:80"

volumes:
  logs:
